# Site
repository: camelop/about
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)
favicon: images/favicon.png

# Personal info
name: Xiaoyuan Liu (刘啸远)
title: Ph.D. Student, EECS, UC Berkeley
email: xiaoyuanliu [at] berkeley [dot] edu
phone: +86 132 - 6229 - 0218
website: littleround.cn
blog: littleround.cn/main
google_scholar_id: vbycUZ4AAAAJ

google_analytics: G-M04GR1LGX2

# Social links
twitter_username: littleRound_cn
github_username:  camelop
linkedin_username: 啸远-刘-b46033190

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://1.gravatar.com/avatar/c017790274c7d1d9a4ee64a8a002c02d91deae5245f6ffe4dfe510101a8a57a2?s=256
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. student in the EECS department at [UC Berkeley](https://www.berkeley.edu/) advised by [Professor Dawn Song](https://people.eecs.berkeley.edu/~dawnsong/). Before joining UC Berkeley, I received my bachelor's degree from [ACM Honors Class](https://acm.sjtu.edu.cn/home), [Shanghai Jiao Tong University](http://en.sjtu.edu.cn/). I am a member of [Berkeley Center for Responsible, Decentralized Intelligence (RDI)](https://rdi.berkeley.edu/), [Initiative for Cryptocurrencies & Contracts Lab (IC3)](https://www.initc3.org/), and [Berkeley Artificial Intelligence Research (BAIR) Lab](https://bair.berkeley.edu/).
  - **Research Interest**: I am broadly interested in **computer security**, **systems**, and **machine learning**, especially building systems that enable secure and privacy-preserving data processing or solve real-world security problems.  
  
  <mark>News</mark>
  - **Aug 2025**: Our [AgentCTF Competition](https://ctf.secure-agent.com/) has been accepted by [IEEE SaTML 2026](https://satml.org/competitions/).
  - **Mar 2025**: *"FHE-based SQL aggregation across millions of records within a minute."* Check out [our paper](https://eprint.iacr.org/2024/1699) accepted to VLDB 2025.  
  - **Jan 2024**: Presenting on Decentralized LLM serving at [IC3 Winter Retreat](https://www.initc3.org/events/2024-01-08-ic3-winter-retreat-2024).
  - **Jul 2023**: Honored to be supported by the [JP Morgan Chase PhD Fellowship 2023](https://www.jpmorgan.com/technology/artificial-intelligence/research-awards/phd-fellowship-2023).

# Service Section

service_content: |
  - Program Committee - COLING [2025](https://coling2025.org/)
  - Program Committee - NIPS [2024](https://neurips.cc/Conferences/2024/ProgramCommittee)
  - Program Committee - FLSys (MLSys workshop) [2023](https://flsys.github.io/)
  - ERC, Session Chair ([Correctness and Security](https://mlsys.org/virtual/2023/session/2501)) - MLSys [2023](https://mlsys.org/Conferences/2023)
  - Program Committee - ACL [2023](https://2023.aclweb.org/)
  - Program Committee - EMNLP [2023](https://2023.emnlp.org/), [2022](https://2022.emnlp.org/), [2021](https://2021.emnlp.org/)
  - Program Committee - CCS [2022](https://www.sigsac.org/ccs/CCS2022/)
  - Coordination Committee - [Responsible Data Summit 2020](https://responsibledata.ai/)

# Project Section

project_content: |
  - AgentBeats [[Overview]](https://docs.agentbeats.org/) [[Competition]](https://rdi.berkeley.edu/agentx-agentbeats.html)
  - CoLearn/CoLink: A Generic Programming Framework for Federated and Decentralized Data Science [[Homepage]](https://colink.app/) [[Talk at NeurIPS 2022 workshop]](https://ai-secure.github.io/DMLW2022/schedule#:~:text=Invited%20Talk%20%237%20Xiaoyuan%20Liu%3A%20CoLearn%3A%20Decentralized%20Programming%20for%20Decentralized%20Data%20Science) 
  - MPC4F (Multi-Party Computation for Fairness) [[News (Meta AI)]](https://ai.facebook.com/blog/assessing-fairness-of-our-products-while-protecting-peoples-privacy) [[News (Oasis Lab)]](https://medium.com/oasislabs/oasis-labs-partners-with-meta-to-assess-fairness-for-its-ai-models-97e153d707ef)

# Honors Section
honor_title: Honors and Awards
honor_content: |
  - RDI Frontier Fellowship [2024]
  - JP Morgan Chase PhD Fellowship [[2023]](https://www.jpmorgan.com/technology/artificial-intelligence/research-awards/phd-fellowship-2023)
  - Berkeley EECS Department Fellowship [2020]
  - Shanghai Excellent Graduate [2020]
  - Outstanding Student Cadre **(Top 0.8%, SJTU)** [2018]
  - Academic Excellence Scholarship [2017, 2018, 2019]
  - Zhiyuan Honorary Scholarship [2016, 2017, 2018, 2019]
  - KoGuan Encouragement Scholarship **(Top 0.3%, SJTU)** [2017]
  - The 32nd China's National Olympiad in Informatics (NOI) Silver Medal [2015]

# Projects Section
projects_title: Selected Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Research Experiences #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Misc #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Materials**
  - [CV (2025)](https://xiaoyuanliu.cn/assets/cv_xiaoyuanliu_ucb_2025_6_d1.pdf)
  - [Bio](https://gist.githubusercontent.com/camelop/97952fd2742b357e585727e0adf2e82f/raw/397a7f11b5d7ef577857fe471993695f963a417c/xliu_bio_2025.txt)
  - [CV (2019, outdated)](https://littleround.cn/static/personal/cv_xiaoyuanliu_SJTU_2019_12.pdf)

  **Teaching Experience**
  - **Teaching Assistant** [Entrepreneurship In Web3 - Fall 2022](https://rdi.berkeley.edu/course/entrepreneurship-in-web3)
  - **Teaching Assistant** [Decentralized Finance - Fall 2021](https://rdi.berkeley.edu/berkeley-defi/f21)
  - **Student Instructor** [Principle and Practice of Computer Algorithms - Summer 2018](https://acm.sjtu.edu.cn/wiki/PPCA_2018)
  - **Lead Teaching Assistant** [Data Structures - Spring 2018](https://acm.sjtu.edu.cn/wiki/Data_Structures_2018)
  - **Lead Teaching Assistant** [C++ Programming (A) - Fall 2017](https://acm.sjtu.edu.cn/wiki/Programming_2017)

  **Activities**
  - Student Council Vice President, Zhiyuan College, SJTU - 2018
  - Head of the Department of Culture and Sports, Student Union, Zhiyuan College, SJTU - 2017

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
